"""Age and stability metrics — old-growth vs seedling classification."""

import os
from datetime import datetime, timezone
from typing import Dict, Optional, Tuple

from .models import ModuleMetrics


# Stability tiers based on days since last change
STABILITY_TIERS = {
    "seedling": (0, 30),        # New, recently changed
    "sapling": (31, 180),       # Young, still evolving
    "mature": (181, 730),       # Stable, regular maintenance
    "old_growth": (731, float("inf")),  # Ancient, barely changing
}

# Age classifications
AGE_TIERS = {
    "newborn": (0, 7),
    "young": (8, 90),
    "established": (91, 365),
    "old": (366, float("inf")),
}


def classify_stability(days_since_last_change: int) -> str:
    """Classify a module's stability tier.

    Args:
        days_since_last_change: Days since the last commit touched this file.

    Returns:
        Stability tier string: 'seedling', 'sapling', 'mature', or 'old_growth'.
    """
    for tier, (lo, hi) in STABILITY_TIERS.items():
        if lo <= days_since_last_change <= hi:
            return tier
    return "seedling"


def classify_age(age_days: int) -> str:
    """Classify a module's age tier.

    Args:
        age_days: Days since the file was first committed.

    Returns:
        Age tier string.
    """
    for tier, (lo, hi) in AGE_TIERS.items():
        if lo <= age_days <= hi:
            return tier
    return "newborn"


def is_likely_dead(days_since_last_change: int, is_deprecated: bool = False) -> bool:
    """Heuristic: is this module likely dead code?

    Args:
        days_since_last_change: Days since last change.
        is_deprecated: Whether the module is marked deprecated.

    Returns:
        True if the module is likely dead code.
    """
    if is_deprecated and days_since_last_change > 180:
        return True
    if days_since_last_change > 730:  # 2 years
        return True
    return False


def is_likely_generated(filepath: str) -> bool:
    """Heuristic: is this file likely auto-generated?

    Checks for common patterns in filenames.
    """
    basename = os.path.basename(filepath)
    generated_patterns = (
        "_generated", ".generated.", "autogenerated",
        ".pb.", "_pb2.", "_pb.", ".proto.",
        "__init__.py",  # Often generated, but we keep it as library
    )
    # More specific: check for generated markers in filename
    specific = ("_generated", ".generated", "_pb2", "_pb.py", ".pb.py")
    for pattern in specific:
        if pattern in basename:
            return True
    return False


def is_likely_config(filepath: str) -> bool:
    """Heuristic: is this file a configuration file?"""
    basename = os.path.basename(filepath).lower()
    config_names = (
        "config", "settings", "conf", "setup.cfg",
        "pyproject.toml", "tox.ini", ".flake8",
        "conftest.py",
    )
    for name in config_names:
        if name in basename:
            return True
    return False


def is_likely_entry_point(filepath: str) -> bool:
    """Heuristic: is this file an entry point?"""
    basename = os.path.basename(filepath)
    entry_names = ("main.py", "app.py", "manage.py", "run.py", "cli.py", "wsgi.py", "asgi.py")
    return basename in entry_names


def is_likely_test(filepath: str) -> bool:
    """Heuristic: is this file a test file?"""
    parts = filepath.replace("\\", "/").split("/")
    basename = os.path.basename(filepath)
    return "test" in parts or basename.startswith("test_") or basename.endswith("_test.py")


def is_likely_deprecated(filepath: str, source: Optional[str] = None) -> bool:
    """Heuristic: is this module deprecated?"""
    basename = os.path.basename(filepath)
    if "deprecated" in basename.lower() or "legacy" in basename.lower():
        return True
    if source and "deprecated" in source.lower()[:500]:
        # Check for deprecation markers in the first 500 chars
        import re
        if re.search(r"(?i)(deprecated|DEPRECATED|@deprecated|# deprecated)", source[:500]):
            return True
    return False
